name: customer_app
description: Kiwi Delivery Customer App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  get: ^4.6.6
  carousel_slider: ^5.1.2
  cached_network_image: ^3.3.0
  smooth_page_indicator: ^1.1.0
  lucide_icons_flutter: ^3.1.14
  flutter_svg: ^2.0.10
  supabase_flutter: ^2.1.0
  shimmer: ^3.0.0
  google_maps_flutter: ^2.5.3
  firebase_core: ^4.9.0
  firebase_messaging: ^16.2.2
  geolocator: ^11.0.0
  maps_toolkit: ^3.1.0
  geocoding: ^4.0.0
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  get_storage: ^2.1.1
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/kwi.png"
  min_sdk_android: 21
  background_color_android: "#FFFFFF"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/kwi.png"
  adaptive_icon_foreground_inset: 10
  remove_alpha_ios: true
  web:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/

