// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE4WX7pdUsiqghBpDz9jfc0mLCbsfcGZI',
    appId: '1:214305510491:web:fe1e3ce1100ea92bec5b7e',
    messagingSenderId: '214305510491',
    projectId: 'fresh-enterprise',
    authDomain: 'fresh-enterprise.firebaseapp.com',
    storageBucket: 'fresh-enterprise.firebasestorage.app',
    measurementId: 'G-7SW1QB3GS7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE4WX7pdUsiqghBpDz9jfc0mLCbsfcGZI',
    appId: '1:214305510491:web:44a327f6b901e4a7ec5b7e',
    messagingSenderId: '214305510491',
    projectId: 'fresh-enterprise',
    authDomain: 'fresh-enterprise.firebaseapp.com',
    storageBucket: 'fresh-enterprise.firebasestorage.app',
    measurementId: 'G-5EXSQ9GVY9',
  );
}
